#####################################################
# Used for CI
# Difference between local and this: 
# 1. Only services required for execution is started
# 2. Volumes not used for development are not mounted (especially frontend)
#####################################################

version: "3.8"

x-interactive: &interactive
  stdin_open: true # docker run -i
  tty: true # docker run -t

services:
  db:
    container_name: indeaa_postgres
    image: postgres:13.5-alpine
    restart: &restart-policy unless-stopped
    env_file: &env-file .env
    environment:
      TZ: Australia/Perth
    volumes:
      - ~/docker/indeaa/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *interactive

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - NODE_ENV=development
        - SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
    container_name: indeaa_react
    restart: *restart-policy
    env_file: *env-file
    ports:
      - 3000:3000
    <<: *interactive

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: indeaa_django
    restart: *restart-policy
    env_file: *env-file
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app_code
    <<: *interactive

  # Used for Local development only
  mailhog:
    container_name: indeaa_mailhog
    image: mailhog/mailhog:v1.0.1
    restart: *restart-policy
    env_file: *env-file
    ports:
      - "11003:8025"
      - "1025:1025"
    logging:
      driver: none # Disable logging to console due to amount of logging noise it generates in docker-compose logs