# Generated by Django 3.2.13 on 2022-07-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEvaluationJustification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("justification", models.TextField(blank=True)),
                ("course_evaluation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course_evaluations.courseevaluation")),
                ("eoc_specific", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course_evaluations.eocspecific")),
            ],
        ),
    ]
