# Generated by Django 3.2.13 on 2022-08-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEvaluationJustification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("justification", models.TextField(blank=True)),
                (
                    "development_level",
                    models.IntegerField(choices=[(1, "Foundational"), (2, "Broad And Coherent"), (3, "Advanced"), (4, "Specialist")]),
                ),
                ("course_evaluation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course_evaluations.courseevaluation")),
                ("eoc_specifics", models.ManyToManyField(related_name="justification", to="course_evaluations.EOCSpecific")),
            ],
        ),
    ]
