# Generated by Django 3.2.15 on 2022-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_evaluations", "0003_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseevaluation",
            name="unit_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
