# Generated by Django 3.2.13 on 2022-08-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdocument',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
