# Generated by Django 3.2.13 on 2022-07-19 08:22

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revieweocspecific",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revieweocspecific",
            name="review",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="eoc_specific_reviews", to="reviews.review"),
        ),
        migrations.AddField(
            model_name="revieweocspecific",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ReviewDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_viewed", models.BooleanField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_messages", to="documents.document")),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="reviews.review")),
            ],
        ),
    ]
