# Generated by Django 3.2.13 on 2022-08-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewdocument_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='eoc_date_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
