# Generated by Django 3.2.13 on 2022-08-12 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('isInIntroduction', models.BooleanField(default=False)),
                ('courseEvaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_evaluations.courseevaluation')),
                ('eocGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_evaluations.eocgeneral')),
                ('eocSpecific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_evaluations.eocspecific')),
            ],
        ),
    ]
