# Generated by Django 3.2.13 on 2022-07-19 07:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_evaluations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_introduction", models.BooleanField()),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eoc_generals", models.ManyToManyField(to="course_evaluations.EOCGeneral")),
                ("eoc_specifics", models.ManyToManyField(to="course_evaluations.EOCSpecific")),
            ],
        ),
    ]
