# Generated by Django 3.2.13 on 2022-08-16 06:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_evaluations", "0002_courseevaluationjustification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("is_introduction", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_evaluation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course_evaluations.courseevaluation")),
                ("eoc_generals", models.ManyToManyField(to="course_evaluations.EOCGeneral")),
                ("eoc_specifics", models.ManyToManyField(to="course_evaluations.EOCSpecific")),
            ],
        ),
    ]
