# Generated by Django 3.2.13 on 2022-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_evaluations', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='eocGeneral',
        ),
        migrations.AddField(
            model_name='documents',
            name='eocGeneral',
            field=models.ManyToManyField(to='course_evaluations.EOCGeneral'),
        ),
        migrations.RemoveField(
            model_name='documents',
            name='eocSpecific',
        ),
        migrations.AddField(
            model_name='documents',
            name='eocSpecific',
            field=models.ManyToManyField(to='course_evaluations.EOCSpecific'),
        ),
    ]
